FROM ubuntu:latest

# TODO (GM): Run container as a dedicated user instead of root?

RUN apt update &&\
    apt upgrade -y &&\
    apt install -y gcc &&\
    apt install -y curl &&\
    sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

RUN mkdir /opt/c-webserver
VOLUME [ "/opt/c-webserver" ]

WORKDIR /opt/c-webserver

# Use this alternative entrypoint for debugging.
# With this you will have to start the server manually (enter the container and type `task run`)
#  but the container will not exit once you kill the server.
# You can use this for debugging purposes - especially in combination with the mounted volume.
# ENTRYPOINT ["tail", "-f", "/dev/null"]

ENTRYPOINT ["task", "run"]
