version: '3'

tasks:
  run:
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - task build OUTPUT_FOLDER='{{ .OUTPUT_FOLDER }}' CFLAGS='{{ .CFLAGS }}'
      - './{{ .OUTPUT_FOLDER }}/server.out'

  run-test:
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - task build-test OUTPUT_FOLDER='{{ .OUTPUT_FOLDER }}' CFLAGS='{{ .CFLAGS }}'
      - './{{ .OUTPUT_FOLDER }}/client.out'

  build:
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - task build-linux OUTPUT_FOLDER='{{ .OUTPUT_FOLDER }}' CFLAGS='{{ .CFLAGS }}'
      - task build-windows OUTPUT_FOLDER='{{ .OUTPUT_FOLDER }}' CFLAGS='{{ .CFLAGS }}'
    silent: true

  build-linux:
    platforms: [linux, darwin]
    sources:
      - src/*.c
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - task build-shell -f MAIN_FILE="src/main.c" OUT_FILE="server.out"
    generates:
      - '{{ .OUTPUT_FOLDER }}/server.out'
      - '{{ .OUTPUT_FOLDER }}/*.o'

  build-windows:
    platforms: [windows]
    sources:
      - src/*.c
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - Powershell.exe ./util/compile.ps1
    generates:
      - '{{ .OUTPUT_FOLDER }}/server.out'
      - '{{ .OUTPUT_FOLDER }}/*.o'

  build-test:
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - task build-test-linux OUTPUT_FOLDER='{{ .OUTPUT_FOLDER }}' CFLAGS='{{ .CFLAGS }}'
      - task build-test-windows OUTPUT_FOLDER='{{ .OUTPUT_FOLDER }}' CFLAGS='{{ .CFLAGS }}'
    silent: true

  build-test-linux:
    platforms: [linux, darwin]
    sources:
      - src/*.c
      - exclude: src/main.c
      - test/test-client.c
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - task build-shell -f MAIN_FILE="test/test-client.c" OUT_FILE="client.out"
    generates:
      - '{{ .OUTPUT_FOLDER }}/server.out'
      - '{{ .OUTPUT_FOLDER }}/*.o'

  build-test-windows:
    platforms: [windows]
    sources:
      - src/*.c
      - exclude: src/main.c
      - test/test-client.c
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - echo "build-test-windows is not implemented!"
    generates:
      - '{{ .OUTPUT_FOLDER }}/server.out'
      - '{{ .OUTPUT_FOLDER }}/*.o'

  build-shell:
    # No platform restriction, might also be run on windows under e.g. git bash
    sources:
      - src/*.c
      - exclude: src/main.c
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
      MAIN_FILE: '{{ default "src/main.c" .MAIN_FILE }}'
      OUT_FILE: '{{ default "server.out" .OUT_FILE }}'
    cmds:
      - rm -rf '{{ .OUTPUT_FOLDER }}'
      - mkdir '{{ .OUTPUT_FOLDER }}'
      - for: sources
        cmd: gcc {{ .CFLAGS }} "$(echo '{{ .ITEM }}' | sed -r 's/\\/\//')" -o "$(echo '{{ .ITEM }}' | sed -r 's/\\/\//' | sed -r 's/\.c$/\.o/' | sed 's/src/{{ .OUTPUT_FOLDER }}/')" -c
      - echo "Using {{ .MAIN_FILE }} as the main file"
      - gcc {{ .CFLAGS }} "$(echo '{{ .MAIN_FILE }}' | sed -r 's/\\/\//')" -o "$(echo '{{ .MAIN_FILE }}' | sed -r 's/\\/\//' | sed -r 's/\.c$/\.o/' | sed 's/src/{{ .OUTPUT_FOLDER }}/' | sed 's/test/{{ .OUTPUT_FOLDER }}/')" -c
      - gcc {{ .CFLAGS }} -o '{{ .OUTPUT_FOLDER }}/{{ .OUT_FILE }}' $(find './{{ .OUTPUT_FOLDER }}' -type f -iwholename '*.o' | xargs echo)
    generates:
      - '{{ .OUTPUT_FOLDER }}/server.out'
      - '{{ .OUTPUT_FOLDER }}/*.o'

  test:
    cmds:
      - task test-linux
      - task test-windows
    silent: true

  test-linux:
    platforms: [linux, darwin]
    cmds:
      - task test-shell

  test-windows:
    platforms: [windows]
    cmds:
      - Powershell.exe ./util/run-tests.ps1

  test-shell:
    cmds:
      - ./util/run-tests.sh
