name: compile-check
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make
      # TODO (GM): Add unit/integration tests and add them here!
